
package main;

import java.util.ArrayList;
import javax.swing.ImageIcon;


public class Test extends javax.swing.JFrame {

     Kullanıcı kullanıcı = new Kullanıcı(1,"Kullanıcı", 0);
     Bilgisayar bot = new Bilgisayar(2,"Bilgisayar", 0);
     
     Futbolcu alex = new Futbolcu(85,70,80,"Alex de Souza","Fenerbahçe","/kartlar/Alex.png"); 
     Futbolcu messi = new Futbolcu(95,90,100,"Lionel Messi","Barcelona","/kartlar/Messi.png");
     Futbolcu ronaldo= new Futbolcu(100,90,95,"Cristiano Ronaldo","Real Madrid","/kartlar/Ronaldo.png");
     Futbolcu tsubasa = new Futbolcu(100,100,100,"Oozora Tsubasa","Nankatsu","/kartlar/Tsubasa.png");
     Futbolcu neymar = new Futbolcu(90,85,80,"Neymar Junior","Paris Saint-Germain","/kartlar/Neymar.png");
     Futbolcu salah = new Futbolcu(80,75,75,"Muhammed Salah","Liverpool","/kartlar/Salah.png");
     Futbolcu maradona = new Futbolcu(90,80,90,"Diego Maradona","Napoli","/kartlar/Maradona.png");
     Futbolcu ronaldinho = new Futbolcu(75,65,85,"Ronaldinho Gaucho","Milan","/kartlar/Ronaldinho.png");
     
     Basketbolcu kobe = new Basketbolcu(80,80,80,"Kobe Bryant","Los Angeles Lakers","/kartlar/kobe.png");
     Basketbolcu lebron = new Basketbolcu(80,100,90,"LeBron James","Los Angeles Lakers","/kartlar/lebron.png");
     Basketbolcu jordan = new Basketbolcu(80,90,80,"Micheal Jordan","Chicago Bulls","/kartlar/jordan.png");
     Basketbolcu shaquille = new Basketbolcu(80,80,90,"Shaquille O'Neal","Miami Heat","/kartlar/shaq.png");
     Basketbolcu cedi = new Basketbolcu(80,80,90,"Cedi Osman","Cleveland Cavaliers","/kartlar/cedi.png");
     Basketbolcu hidayet = new Basketbolcu(80,80,90,"Hidayet Türkoğlu","Sacramento Kings","/kartlar/hido.png");
     Basketbolcu kagami = new Basketbolcu(80,100,100,"Kagami Taiga","Seirin","/kartlar/kagami.png");
     Basketbolcu stephen = new Basketbolcu(80,60,70,"Stephen Curry","Golden State Warriors","/kartlar/step.png");
     
     
     
     ImageIcon arka = new ImageIcon(getClass().getResource("/kartlar/Adsz.png"));
     
     ArrayList<Futbolcu> list1 = new ArrayList<Futbolcu>();
     ArrayList<Basketbolcu> list2 = new ArrayList<Basketbolcu>();
     int fKartKontrol = 0;
     int bKartKontrol = 0;
    
    
    public Test() {
     list1.add(alex);
     list1.add(messi);
     list1.add(ronaldo);
     list1.add(tsubasa);
     list1.add(neymar);
     list1.add(salah);
     list1.add(maradona);
     list1.add(ronaldinho);
     list2.add(kobe);
     list2.add(lebron);
     list2.add(jordan);
     list2.add(shaquille);
     list2.add(cedi);
     list2.add(hidayet);
     list2.add(kagami);
     list2.add(stephen);
     
     bot.getSayıListesi().add(0);
     bot.getSayıListesi().add(1);
     bot.getSayıListesi().add(2);
     bot.getSayıListesi().add(3);
     bot.getSayıListesi1().add(0);
     bot.getSayıListesi1().add(1);
     bot.getSayıListesi1().add(2);
     bot.getSayıListesi1().add(3);
     
     
     initComponents();
     Kullanıcı1.setVisible(false);
     Kullanıcı2.setVisible(false);
     Kullanıcı3.setVisible(false);
     Kullanıcı4.setVisible(false);
     Kullanıcı5.setVisible(false);
     Kullanıcı6.setVisible(false);
     Kullanıcı7.setVisible(false);
     Kullanıcı8.setVisible(false);
     Bot1.setVisible(false);
     Bot2.setVisible(false);
     Bot3.setVisible(false);
     Bot4.setVisible(false);
     Bot5.setVisible(false);
     Bot6.setVisible(false);
     Bot7.setVisible(false);
     Bot8.setVisible(false);
     BotAd.setVisible(false);
     KullanıcıAd.setVisible(false);
     BotSkor.setVisible(false);
     KullanıcıSkor.setVisible(false);
     BotOrta.setVisible(false);
     KullanıcıOrta.setVisible(false);
     Karşılaştırma.setVisible(false);
     Pozisyon.setVisible(false);
     kartlarıÇek.setVisible(false);
     bitiş.setVisible(false);
     
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Başla = new javax.swing.JButton();
        Kullanıcı1 = new javax.swing.JButton();
        Kullanıcı2 = new javax.swing.JButton();
        Kullanıcı3 = new javax.swing.JButton();
        Kullanıcı4 = new javax.swing.JButton();
        Kullanıcı5 = new javax.swing.JButton();
        Kullanıcı6 = new javax.swing.JButton();
        Kullanıcı7 = new javax.swing.JButton();
        Kullanıcı8 = new javax.swing.JButton();
        Bot1 = new javax.swing.JLabel();
        Bot2 = new javax.swing.JLabel();
        Bot3 = new javax.swing.JLabel();
        Bot4 = new javax.swing.JLabel();
        Bot5 = new javax.swing.JLabel();
        Bot6 = new javax.swing.JLabel();
        Bot7 = new javax.swing.JLabel();
        Bot8 = new javax.swing.JLabel();
        KullanıcıOrta = new javax.swing.JLabel();
        BotOrta = new javax.swing.JLabel();
        KullanıcıAd = new javax.swing.JTextField();
        BotAd = new javax.swing.JTextField();
        Pozisyon = new javax.swing.JTextField();
        Karşılaştırma = new javax.swing.JTextField();
        BotSkor = new javax.swing.JTextField();
        KullanıcıSkor = new javax.swing.JTextField();
        bitiş = new javax.swing.JTextField();
        kartlarıÇek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Futbolcular ve Basketbolcular");
        getContentPane().setLayout(null);

        Başla.setIcon(new javax.swing.ImageIcon("D:\\Prolab\\Proje 2\\ProjeFotoları\\play.png")); // NOI18N
        Başla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaşlaActionPerformed(evt);
            }
        });
        getContentPane().add(Başla);
        Başla.setBounds(660, 340, 240, 100);
        Başla.getAccessibleContext().setAccessibleName("jButton1");

        Kullanıcı1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı1ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı1);
        Kullanıcı1.setBounds(40, 590, 150, 200);

        Kullanıcı2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı2ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı2);
        Kullanıcı2.setBounds(210, 590, 150, 200);

        Kullanıcı3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı3ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı3);
        Kullanıcı3.setBounds(400, 590, 150, 200);

        Kullanıcı4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı4ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı4);
        Kullanıcı4.setBounds(583, 593, 150, 200);

        Kullanıcı5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı5ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı5);
        Kullanıcı5.setBounds(803, 593, 150, 200);

        Kullanıcı6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı6ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı6);
        Kullanıcı6.setBounds(993, 593, 150, 200);

        Kullanıcı7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı7ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı7);
        Kullanıcı7.setBounds(1183, 593, 150, 200);

        Kullanıcı8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kullanıcı8ActionPerformed(evt);
            }
        });
        getContentPane().add(Kullanıcı8);
        Kullanıcı8.setBounds(1373, 593, 150, 200);

        Bot1.setText("jLabel2");
        Bot1.setPreferredSize(new java.awt.Dimension(150, 200));
        getContentPane().add(Bot1);
        Bot1.setBounds(30, 20, 150, 200);

        Bot2.setText("jLabel3");
        getContentPane().add(Bot2);
        Bot2.setBounds(210, 20, 150, 200);

        Bot3.setText("jLabel4");
        getContentPane().add(Bot3);
        Bot3.setBounds(390, 20, 150, 200);

        Bot4.setText("jLabel5");
        getContentPane().add(Bot4);
        Bot4.setBounds(590, 20, 150, 200);

        Bot5.setText("jLabel6");
        getContentPane().add(Bot5);
        Bot5.setBounds(810, 20, 150, 200);

        Bot6.setText("jLabel7");
        getContentPane().add(Bot6);
        Bot6.setBounds(1000, 20, 150, 200);

        Bot7.setText("jLabel8");
        getContentPane().add(Bot7);
        Bot7.setBounds(1180, 20, 150, 200);
        getContentPane().add(Bot8);
        Bot8.setBounds(1370, 20, 150, 200);

        KullanıcıOrta.setText("jLabel10");
        getContentPane().add(KullanıcıOrta);
        KullanıcıOrta.setBounds(580, 290, 150, 200);

        BotOrta.setText("jLabel11");
        getContentPane().add(BotOrta);
        BotOrta.setBounds(800, 290, 150, 200);

        KullanıcıAd.setEditable(false);
        KullanıcıAd.setText("Kullanıcı");
        getContentPane().add(KullanıcıAd);
        KullanıcıAd.setBounds(620, 240, 90, 30);

        BotAd.setEditable(false);
        BotAd.setText("Bot");
        getContentPane().add(BotAd);
        BotAd.setBounds(810, 240, 90, 30);

        Pozisyon.setEditable(false);
        getContentPane().add(Pozisyon);
        Pozisyon.setBounds(120, 300, 240, 40);

        Karşılaştırma.setEditable(false);
        getContentPane().add(Karşılaştırma);
        Karşılaştırma.setBounds(120, 410, 240, 40);

        BotSkor.setEditable(false);
        getContentPane().add(BotSkor);
        BotSkor.setBounds(1280, 310, 100, 30);

        KullanıcıSkor.setEditable(false);
        getContentPane().add(KullanıcıSkor);
        KullanıcıSkor.setBounds(1280, 440, 100, 30);

        bitiş.setEditable(false);
        getContentPane().add(bitiş);
        bitiş.setBounds(680, 510, 190, 40);

        kartlarıÇek.setText("KARTLARI ÇEK!");
        kartlarıÇek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartlarıÇekActionPerformed(evt);
            }
        });
        getContentPane().add(kartlarıÇek);
        kartlarıÇek.setBounds(720, 510, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Prolab\\Proje 2\\ProjeFotoları\\Background.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1550, 828);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1550, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaşlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaşlaActionPerformed
        Başla.setVisible(false);
        
        for(int i=0;i<4;i++){
        kullanıcı.KartDagit1(list1);
        kullanıcı.KartDagit2(list2);
        bot.KartDagit1(list1);
        bot.KartDagit2(list2);
        }
        
        Kullanıcı1.setIcon(kullanıcı.getKartListesi1().get(0).kart);
        Kullanıcı2.setIcon(kullanıcı.getKartListesi1().get(1).kart);
        Kullanıcı3.setIcon(kullanıcı.getKartListesi1().get(2).kart);
        Kullanıcı4.setIcon(kullanıcı.getKartListesi1().get(3).kart);
        Kullanıcı5.setIcon(kullanıcı.getKartListesi2().get(0).kart);
        Kullanıcı6.setIcon(kullanıcı.getKartListesi2().get(1).kart);
        Kullanıcı7.setIcon(kullanıcı.getKartListesi2().get(2).kart);
        Kullanıcı8.setIcon(kullanıcı.getKartListesi2().get(3).kart);
        Bot1.setIcon(arka);
        Bot2.setIcon(arka);
        Bot3.setIcon(arka);
        Bot4.setIcon(arka);
        Bot5.setIcon(arka);
        Bot6.setIcon(arka);
        Bot7.setIcon(arka);
        Bot8.setIcon(arka);
        
        BotSkor.setText("Bot: "+bot.getSkor());
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        
        
        
        
        
        Kullanıcı1.setVisible(true);
        Kullanıcı2.setVisible(true);
        Kullanıcı3.setVisible(true);
        Kullanıcı4.setVisible(true);
        Kullanıcı5.setVisible(true);
        Kullanıcı6.setVisible(true);
        Kullanıcı7.setVisible(true);
        Kullanıcı8.setVisible(true);
        Bot1.setVisible(true);
        Bot2.setVisible(true);
        Bot3.setVisible(true);
        Bot4.setVisible(true);
        Bot5.setVisible(true);
        Bot6.setVisible(true);
        Bot7.setVisible(true);
        Bot8.setVisible(true);
        BotSkor.setVisible(true);
        KullanıcıSkor.setVisible(true);
        BotAd.setVisible(true);
        KullanıcıAd.setVisible(true);
        
        
    }//GEN-LAST:event_BaşlaActionPerformed

    private void Kullanıcı2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı2ActionPerformed
      
      int [] sayı = bot.kartSeç(1);
      
      Kullanıcı2.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı2.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot1.setVisible(false);
      Bot1.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot2.setVisible(false);
      Bot2.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot3.setVisible(false);
      Bot3.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot4.setVisible(false);
      Bot4.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(bKartKontrol<4)
      {
      Kullanıcı1.setEnabled(false);
      Kullanıcı2.setEnabled(false);
      Kullanıcı3.setEnabled(false);
      Kullanıcı4.setEnabled(false);
      }
      Kullanıcı5.setEnabled(true);
      Kullanıcı6.setEnabled(true);
      Kullanıcı7.setEnabled(true);
      Kullanıcı8.setEnabled(true);
      
      if(fKartKontrol==3 && bKartKontrol==4 &&kullanıcı.getKartListesi1().get(1).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı() && kullanıcı.getKartListesi1().get(1).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş() && kullanıcı.getKartListesi1().get(1).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       fKartKontrol++;
      }
    
      else{
          
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : PENALTI");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(1).getPenaltı()>bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi1().get(1).getPenaltı()<bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(1).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
       
        
         
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : SERBEST VURUŞ");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(1).getserbestVuruş()>bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(1).getserbestVuruş()<bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(1).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
        
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : ÇALIM");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(1).getÇalım()>bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(1).getÇalım()<bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(1).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
       
      }
      }
      }
        if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        
        } 
            
    }//GEN-LAST:event_Kullanıcı2ActionPerformed

    private void Kullanıcı1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı1ActionPerformed
        
      int [] sayı = bot.kartSeç(1);
      
      Kullanıcı1.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı1.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot1.setVisible(false);
      Bot1.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot2.setVisible(false);
      Bot2.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot3.setVisible(false);
      Bot3.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot4.setVisible(false);
      Bot4.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(bKartKontrol<4)
      {
      Kullanıcı1.setEnabled(false);
      Kullanıcı2.setEnabled(false);
      Kullanıcı3.setEnabled(false);
      Kullanıcı4.setEnabled(false);
      }
      Kullanıcı5.setEnabled(true);
      Kullanıcı6.setEnabled(true);
      Kullanıcı7.setEnabled(true);
      Kullanıcı8.setEnabled(true);
      
      if(fKartKontrol==3 && bKartKontrol==4 &&kullanıcı.getKartListesi1().get(0).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı() && kullanıcı.getKartListesi1().get(0).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş() && kullanıcı.getKartListesi1().get(0).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       fKartKontrol++;
      }
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : PENALTI");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(0).getPenaltı()>bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(0).getPenaltı()<bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(0).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
        
         
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : SERBEST VURUŞ");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(0).getserbestVuruş()>bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(0).getserbestVuruş()<bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(0).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
        
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : ÇALIM");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(0).getÇalım()>bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(0).getÇalım()<bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(0).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
         
      }
      }
      }
      
        if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        } 
        
    }//GEN-LAST:event_Kullanıcı1ActionPerformed

    private void Kullanıcı3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı3ActionPerformed
        
      int [] sayı = bot.kartSeç(1);
      
      Kullanıcı3.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı3.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot1.setVisible(false);
      Bot1.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot2.setVisible(false);
      Bot2.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot3.setVisible(false);
      Bot3.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot4.setVisible(false);
      Bot4.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(bKartKontrol<4)
      {
      Kullanıcı1.setEnabled(false);
      Kullanıcı2.setEnabled(false);
      Kullanıcı3.setEnabled(false);
      Kullanıcı4.setEnabled(false);
      }
      Kullanıcı5.setEnabled(true);
      Kullanıcı6.setEnabled(true);
      Kullanıcı7.setEnabled(true);
      Kullanıcı8.setEnabled(true);
      
      if(fKartKontrol==3 && bKartKontrol==4 &&kullanıcı.getKartListesi1().get(2).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı() && kullanıcı.getKartListesi1().get(2).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş() && kullanıcı.getKartListesi1().get(2).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       fKartKontrol++;
      }
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : PENALTI");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(2).getPenaltı()>bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(2).getPenaltı()<bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(2).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
        
         
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : SERBEST VURUŞ");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(2).getserbestVuruş()>bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(2).getserbestVuruş()<bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(2).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
         
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : ÇALIM");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(2).getÇalım()>bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(2).getÇalım()<bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(2).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
         
      }
      }
      }
        if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        } 
        
    }//GEN-LAST:event_Kullanıcı3ActionPerformed

    private void Kullanıcı4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı4ActionPerformed
        
      int [] sayı = bot.kartSeç(1);
      
      Kullanıcı4.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı4.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot1.setVisible(false);
      Bot1.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot2.setVisible(false);
      Bot2.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot3.setVisible(false);
      Bot3.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot4.setVisible(false);
      Bot4.setIcon(bot.getKartListesi1().get(sayı[1]).kart);
      }
      if(bKartKontrol<4)
      {
      Kullanıcı1.setEnabled(false);
      Kullanıcı2.setEnabled(false);
      Kullanıcı3.setEnabled(false);
      Kullanıcı4.setEnabled(false);
      }
      Kullanıcı5.setEnabled(true);
      Kullanıcı6.setEnabled(true);
      Kullanıcı7.setEnabled(true);
      Kullanıcı8.setEnabled(true);
      
      if(fKartKontrol==3 && bKartKontrol==4 &&kullanıcı.getKartListesi1().get(3).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı() && kullanıcı.getKartListesi1().get(3).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş() && kullanıcı.getKartListesi1().get(3).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       fKartKontrol++;
      }
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : PENALTI");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(3).getPenaltı()>bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi1().get(3).getPenaltı()<bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(3).getPenaltı()==bot.getKartListesi1().get(sayı[1]).getPenaltı())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
        
         
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : SERBEST VURUŞ");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(3).getserbestVuruş()>bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi1().get(3).getserbestVuruş()<bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(3).getserbestVuruş()==bot.getKartListesi1().get(sayı[1]).getserbestVuruş())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
         
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : ÇALIM");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi1().get(3).getÇalım()>bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi1().get(3).getÇalım()<bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        fKartKontrol++;
        bot.getSayıListesi().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi1().get(3).getÇalım()==bot.getKartListesi1().get(sayı[1]).getÇalım())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı5.setEnabled(false);
        Kullanıcı6.setEnabled(false);
        Kullanıcı7.setEnabled(false);
        Kullanıcı8.setEnabled(false);
          
      }
      }
      }
        if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        } 
        
    }//GEN-LAST:event_Kullanıcı4ActionPerformed

    private void Kullanıcı5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı5ActionPerformed
        
      int [] sayı = bot.kartSeç(2);
      
      Kullanıcı5.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı5.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot5.setVisible(false);
      Bot5.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot6.setVisible(false);
      Bot6.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot7.setVisible(false);
      Bot7.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot8.setVisible(false);
      Bot8.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      Kullanıcı1.setEnabled(true);
      Kullanıcı2.setEnabled(true);
      Kullanıcı3.setEnabled(true);
      Kullanıcı4.setEnabled(true);
      if(fKartKontrol<4)
      {
      Kullanıcı5.setEnabled(false);
      Kullanıcı6.setEnabled(false);
      Kullanıcı7.setEnabled(false);
      Kullanıcı8.setEnabled(false);
      }
      
      if(fKartKontrol==4 && bKartKontrol==3 && kullanıcı.getKartListesi2().get(0).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik() && kullanıcı.getKartListesi2().get(0).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük() && kullanıcı.getKartListesi2().get(0).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       bKartKontrol++;
      }
    
      
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : İKİLİK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(0).getIkilik()>bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(0).getIkilik()<bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(0).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : ÜÇLÜK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(0).getÜçlük()>bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
        
      }
      if(kullanıcı.getKartListesi2().get(0).getÜçlük()<bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(0).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : REBOUND");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(0).getRebound()>bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(0).getRebound()<bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(0).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
          
      }
      }
      }  
      if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        }
        
    }//GEN-LAST:event_Kullanıcı5ActionPerformed

    private void Kullanıcı6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı6ActionPerformed
        
      int [] sayı = bot.kartSeç(2);
      
      Kullanıcı6.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı6.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot5.setVisible(false);
      Bot5.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot6.setVisible(false);
      Bot6.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot7.setVisible(false);
      Bot7.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot8.setVisible(false);
      Bot8.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      Kullanıcı1.setEnabled(true);
      Kullanıcı2.setEnabled(true);
      Kullanıcı3.setEnabled(true);
      Kullanıcı4.setEnabled(true);
      if(fKartKontrol<4)
      {
      Kullanıcı5.setEnabled(false);
      Kullanıcı6.setEnabled(false);
      Kullanıcı7.setEnabled(false);
      Kullanıcı8.setEnabled(false);
      }
      
      if(fKartKontrol==4 && bKartKontrol==3 && kullanıcı.getKartListesi2().get(1).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik() && kullanıcı.getKartListesi2().get(1).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük() && kullanıcı.getKartListesi2().get(1).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       bKartKontrol++;
      }
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : İKİLİK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(1).getIkilik()>bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(1).getIkilik()<bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(1).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
          
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : ÜÇLÜK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(1).getÜçlük()>bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(1).getÜçlük()<bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(1).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
          
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : REBOUND");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(1).getRebound()>bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(1).getRebound()<bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(1).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      }  
      if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        }
        
    }//GEN-LAST:event_Kullanıcı6ActionPerformed

    private void Kullanıcı7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı7ActionPerformed
        
      int [] sayı = bot.kartSeç(2);
      
      Kullanıcı7.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı7.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot5.setVisible(false);
      Bot5.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot6.setVisible(false);
      Bot6.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot7.setVisible(false);
      Bot7.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot8.setVisible(false);
      Bot8.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      Kullanıcı1.setEnabled(true);
      Kullanıcı2.setEnabled(true);
      Kullanıcı3.setEnabled(true);
      Kullanıcı4.setEnabled(true);
      if(fKartKontrol<4)
      {
      Kullanıcı5.setEnabled(false);
      Kullanıcı6.setEnabled(false);
      Kullanıcı7.setEnabled(false);
      Kullanıcı8.setEnabled(false);
      }
      
      if(fKartKontrol==4 && bKartKontrol==3 && kullanıcı.getKartListesi2().get(2).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik() && kullanıcı.getKartListesi2().get(2).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük() && kullanıcı.getKartListesi2().get(2).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       bKartKontrol++;
      }
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : İKİLİK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(2).getIkilik()>bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(2).getIkilik()<bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(2).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
          
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : ÜÇLÜK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(2).getÜçlük()>bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(2).getÜçlük()<bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(2).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : REBOUND");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(2).getRebound()>bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(2).getRebound()<bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(2).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      }  
      if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        }
        
    }//GEN-LAST:event_Kullanıcı7ActionPerformed

    private void Kullanıcı8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kullanıcı8ActionPerformed
        
      int [] sayı = bot.kartSeç(2);
      
      Kullanıcı8.setVisible(false);
      KullanıcıOrta.setIcon(Kullanıcı8.getIcon());
      KullanıcıOrta.setVisible(true);
      BotOrta.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      BotOrta.setVisible(true);
      if(sayı[1]==0)
      {
      Bot5.setVisible(false);
      Bot5.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==1)
      {
      Bot6.setVisible(false);
      Bot6.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==2)
      {
      Bot7.setVisible(false);
      Bot7.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      if(sayı[1]==3)
      {
      Bot8.setVisible(false);
      Bot8.setIcon(bot.getKartListesi2().get(sayı[1]).kart);
      }
      Kullanıcı1.setEnabled(true);
      Kullanıcı2.setEnabled(true);
      Kullanıcı3.setEnabled(true);
      Kullanıcı4.setEnabled(true);
      if(fKartKontrol<4)
      {
      Kullanıcı5.setEnabled(false);
      Kullanıcı6.setEnabled(false);
      Kullanıcı7.setEnabled(false);
      Kullanıcı8.setEnabled(false);
      }
      
      if(fKartKontrol==4 && bKartKontrol==3 && kullanıcı.getKartListesi2().get(3).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik() && kullanıcı.getKartListesi2().get(3).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük() && kullanıcı.getKartListesi2().get(3).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound()){
       Karşılaştırma.setText("BÜTÜN POZİSYONLAR EŞİT, BERABERE!");
       bKartKontrol++;
      }
      else{
      int poz = pozisyonBelirle();
      
      if(poz==1)
      {
      Pozisyon.setText("POZİSYON : İKİLİK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(3).getIkilik()>bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(3).getIkilik()<bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(3).getIkilik()==bot.getKartListesi2().get(sayı[1]).getIkilik())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot Puanı : "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      
      if(poz==2)
      {
      Pozisyon.setText("POZİSYON : ÜÇLÜK");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(3).getÜçlük()>bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(3).getÜçlük()<bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(3).getÜçlük()==bot.getKartListesi2().get(sayı[1]).getÜçlük())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
         
      }
      }
      
      if(poz==3)
      {
      Pozisyon.setText("POZİSYON : REBOUND");
      Pozisyon.setVisible(true);
      if(kullanıcı.getKartListesi2().get(3).getRebound()>bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        kullanıcı.setSkor(kullanıcı.getSkor() + 10);
        Karşılaştırma.setText("KULLANICI KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
         
      }
      if(kullanıcı.getKartListesi2().get(3).getRebound()<bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        bot.setSkor(bot.getSkor() + 10);
        Karşılaştırma.setText("BOT KAZANDI!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı: "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        bKartKontrol++;
        bot.getSayıListesi1().remove(sayı[0]);
          
      }
      if(kullanıcı.getKartListesi2().get(3).getRebound()==bot.getKartListesi2().get(sayı[1]).getRebound())
      {
        Karşılaştırma.setText("BERABERE, KARTLARI GERİ ÇEKİN!");
        Karşılaştırma.setVisible(true);
        KullanıcıSkor.setText("Kullanıcı : "+kullanıcı.getSkor());
        BotSkor.setText("Bot: "+bot.getSkor());
        kartlarıÇek.setVisible(true);
        Kullanıcı1.setEnabled(false);
        Kullanıcı2.setEnabled(false);
        Kullanıcı3.setEnabled(false);
        Kullanıcı4.setEnabled(false);
          
      }
      }
      }  
      if(fKartKontrol == 4 && bKartKontrol == 4)
        {
        Kullanıcı1.setVisible(false);
        Kullanıcı2.setVisible(false);
        Kullanıcı3.setVisible(false);
        Kullanıcı4.setVisible(false);
        Kullanıcı5.setVisible(false);
        Kullanıcı6.setVisible(false);
        Kullanıcı7.setVisible(false);
        Kullanıcı8.setVisible(false);
        Bot1.setVisible(false);
        Bot2.setVisible(false);
        Bot3.setVisible(false);
        Bot4.setVisible(false);
        Bot5.setVisible(false);
        Bot6.setVisible(false);
        Bot7.setVisible(false);
        Bot8.setVisible(false);
        kartlarıÇek.setVisible(false);
        
        if(kullanıcı.getSkor()>bot.getSkor())
        {
        bitiş.setText("OYUNCU KAZANDI.");
        }
        if(kullanıcı.getSkor()<bot.getSkor())
        {
        bitiş.setText("BOT KAZANDI.");
        }
        if(kullanıcı.getSkor()==bot.getSkor())
        {
        bitiş.setText("BERABERE.");
        }
        bitiş.setVisible(true);
        }
        
    }//GEN-LAST:event_Kullanıcı8ActionPerformed

    private void kartlarıÇekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartlarıÇekActionPerformed
        
        if(Kullanıcı1.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı1.getIcon())
       {
        Kullanıcı1.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı5.setEnabled(true);
        Kullanıcı6.setEnabled(true);
        Kullanıcı7.setEnabled(true);
        Kullanıcı8.setEnabled(true);
       }
       if(Kullanıcı2.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı2.getIcon())
       {
        Kullanıcı2.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı5.setEnabled(true);
        Kullanıcı6.setEnabled(true);
        Kullanıcı7.setEnabled(true);
        Kullanıcı8.setEnabled(true);
       }
       if(Kullanıcı3.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı3.getIcon())
       {
        Kullanıcı3.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı5.setEnabled(true);
        Kullanıcı6.setEnabled(true);
        Kullanıcı7.setEnabled(true);
        Kullanıcı8.setEnabled(true);
       }
       if(Kullanıcı4.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı4.getIcon())
       {
        Kullanıcı4.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı5.setEnabled(true);
        Kullanıcı6.setEnabled(true);
        Kullanıcı7.setEnabled(true);
        Kullanıcı8.setEnabled(true);
       }
       if(Kullanıcı5.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı5.getIcon())
       {
        Kullanıcı5.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı1.setEnabled(true);
        Kullanıcı2.setEnabled(true);
        Kullanıcı3.setEnabled(true);
        Kullanıcı4.setEnabled(true);
       }
       if(Kullanıcı6.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı6.getIcon())
       {
        Kullanıcı6.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı1.setEnabled(true);
        Kullanıcı2.setEnabled(true);
        Kullanıcı3.setEnabled(true);
        Kullanıcı4.setEnabled(true);
       }
       if(Kullanıcı7.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı7.getIcon())
       {
        Kullanıcı7.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı1.setEnabled(true);
        Kullanıcı2.setEnabled(true);
        Kullanıcı3.setEnabled(true);
        Kullanıcı4.setEnabled(true);
       }
       if(Kullanıcı8.isVisible()==false && KullanıcıOrta.getIcon() == Kullanıcı8.getIcon())
       {
        Kullanıcı8.setVisible(true);
        KullanıcıOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
        Kullanıcı1.setEnabled(true);
        Kullanıcı2.setEnabled(true);
        Kullanıcı3.setEnabled(true);
        Kullanıcı4.setEnabled(true);
       }
       if(Bot1.isVisible()==false && BotOrta.getIcon() == Bot1.getIcon())
       {
        Bot1.setIcon(arka);
        Bot1.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot2.isVisible()==false && BotOrta.getIcon() == Bot2.getIcon())
       {
        Bot2.setIcon(arka);
        Bot2.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot3.isVisible()==false && BotOrta.getIcon() == Bot3.getIcon())
       {
        Bot3.setIcon(arka);
        Bot3.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot4.isVisible()==false && BotOrta.getIcon() == Bot4.getIcon())
       {
        Bot4.setIcon(arka);
        Bot4.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot5.isVisible()==false && BotOrta.getIcon() == Bot5.getIcon())
       {
        Bot5.setIcon(arka);
        Bot5.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot6.isVisible()==false && BotOrta.getIcon() == Bot6.getIcon())
       {
        Bot6.setIcon(arka);
        Bot6.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot7.isVisible()==false && BotOrta.getIcon() == Bot7.getIcon())
       {
        Bot7.setIcon(arka);
        Bot7.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
       if(Bot8.isVisible()==false && BotOrta.getIcon() == Bot8.getIcon())
       {
        Bot8.setIcon(arka);
        Bot8.setVisible(true);
        BotOrta.setVisible(false);
        kartlarıÇek.setVisible(false);
       }
        
    }//GEN-LAST:event_kartlarıÇekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
     
     
     

             
     
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
     
     
    }
    
    public int pozisyonBelirle(){
      int x =  (int) (Math.random()*3);
      if(x==0)
          return 1;
      else if(x==1)
          return 2;
      else 
          return 3;
    }
         
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Başla;
    private javax.swing.JLabel Bot1;
    private javax.swing.JLabel Bot2;
    private javax.swing.JLabel Bot3;
    private javax.swing.JLabel Bot4;
    private javax.swing.JLabel Bot5;
    private javax.swing.JLabel Bot6;
    private javax.swing.JLabel Bot7;
    private javax.swing.JLabel Bot8;
    private javax.swing.JTextField BotAd;
    private javax.swing.JLabel BotOrta;
    private javax.swing.JTextField BotSkor;
    private javax.swing.JTextField Karşılaştırma;
    private javax.swing.JButton Kullanıcı1;
    private javax.swing.JButton Kullanıcı2;
    private javax.swing.JButton Kullanıcı3;
    private javax.swing.JButton Kullanıcı4;
    private javax.swing.JButton Kullanıcı5;
    private javax.swing.JButton Kullanıcı6;
    private javax.swing.JButton Kullanıcı7;
    private javax.swing.JButton Kullanıcı8;
    private javax.swing.JTextField KullanıcıAd;
    private javax.swing.JLabel KullanıcıOrta;
    private javax.swing.JTextField KullanıcıSkor;
    private javax.swing.JTextField Pozisyon;
    private javax.swing.JTextField bitiş;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kartlarıÇek;
    // End of variables declaration//GEN-END:variables
}